/* Copyright (c) Microsoft Corporation.
 * Licensed under the MIT License. */

/**
 * @file aws_iot_mqtt.h
 *
 * @brief AWS IoT MQTT is the MQTT interface that application layer depends upon.
 *        Not really mandatory since it can be called directly from application code.
 *
 * @note 
 */

#ifndef AWS_IOT_MQTT_H
#define AWS_IOT_MQTT_H

#include <stdint.h>
#include <stdbool.h>

#include "core_mqtt.h"
#include "aws_iot_transport_interface.h"


/**
 * @brief Initialize an IoTMQTT context.
 *
 * @note This function is for integration of the Azure IoT middleware and
 *       the underlying MQTT stack and should in general not be invoked by
 *       applications directly.
 *
 * @param[in] xContext The MQTT context to initialize.
 * @param[in] pxTransportInterface The transport interface to use with the context.
 * @param[in] xGetTimeFunction The time utility function to use with the context.
 * @param[in] xUserCallback The user callback to use with the context to
 * notify about incoming packet events.
 * @param[in] pucNetworkBuffer Network buffer provided for the context.
 * @param[in] xNetworkBufferLength Length of network buffer.
 *
 * @return An MQTTResult_t with the result of the operation.
 */
MQTTStatus_t AwsIoTMQTT_Init( MQTTContext_t * xContext,
                                const TransportInterface_t * pxTransportInterface,
                                MQTTGetCurrentTimeFunc_t xGetTimeFunction,
                                MQTTEventCallback_t xUserCallback,
                                uint8_t * pucNetworkBuffer,
                                size_t xNetworkBufferLength );


/**
 * @brief Establish an MQTT session.
 *
 * @note Last Will and Testament is not used with Azure IoT Hub.
 *
 * This function will send MQTT CONNECT packet and receive a CONNACK packet. The
 * send and receive from the network is done through the transport interface.
 *
 * @param[in] xContext Initialized MQTT context.
 * @param[in] pxConnectInfo MQTT CONNECT packet information.
 * @param[in] pxWillInfo Last Will and Testament. Pass NULL if Last Will and Testament is not used.
 * @param[in] ulMilliseconds Maximum time in milliseconds to wait for a CONNACK packet.
 * @param[out] pxSessionPresent Whether a previous session was present.
 * Only relevant if not establishing a clean session.
 *
 * @return An MQTTResult_t with the result of the operation.
 */
MQTTStatus_t AwsIoTMQTT_Connect( MQTTContext_t * xContext,
                                    const MQTTConnectInfo_t * pxConnectInfo,
                                    const MQTTPublishInfo_t * pxWillInfo,
                                    uint32_t ulMilliseconds,
                                    bool * pxSessionPresent );

/**
 * @brief Sends MQTT SUBSCRIBE for the given list of topic filters to
 * the broker.
 *
 * @param[in] xContext Initialized MQTT context.
 * @param[in] pxSubscriptionList List of MQTT subscription infos.
 * @param[in] xSubscriptionCount The number of elements in pxSubscriptionList.
 * @param[in] usPacketId Packet ID ( generated by MQTT_GetPacketId ).
 *
 * @return An MQTTResult_t with the result of the operation.
 */
MQTTStatus_t AwsIoTMQTT_Subscribe( MQTTContext_t * xContext,
                                    const MQTTSubscribeInfo_t * pxSubscriptionList,
                                    size_t xSubscriptionCount,
                                    uint16_t usPacketId );

/**
 * @brief Publishes a message to the given topic name.
 *
 * @param[in] xContext Initialized MQTT context.
 * @param[in] pxPublishInfo MQTT PUBLISH packet parameters.
 * @param[in] usPacketId packet ID ( generated by MQTT_GetPacketId ).
 *
 * @return An MQTTResult_t with the result of the operation. 
 */
MQTTStatus_t AwsIoTMQTT_Publish( MQTTContext_t * xContext,
                                    const MQTTPublishInfo_t * pxPublishInfo,
                                    uint16_t usPacketId );

/**
 * @brief Sends a MQTT PINGREQ to broker.
 *
 * @param[in] xContext Initialized MQTT context.
 *
 * @return An MQTTResult_t with the result of the operation.
 */
MQTTStatus_t AzureIoTMQTT_Ping( MQTTContext_t * xContext );

/**
 * @brief Sends MQTT UNSUBSCRIBE for the given list of topic filters to
 * the broker.
 *
 * @param[in] xContext Initialized MQTT context.
 * @param[in] pxSubscriptionList List of MQTT subscription infos.
 * @param[in] xSubscriptionCount The number of elements in pxSubscriptionList.
 * @param[in] usPacketId packet ID ( generated by MQTT_GetPacketId ).
 *
 * @return An MQTTResult_t with the result of the operation.
 */
MQTTStatus_t AwsIoTMQTT_Unsubscribe( MQTTContext_t * xContext,
                                        const MQTTSubscribeInfo_t * pxSubscriptionList,
                                        size_t xSubscriptionCount,
                                        uint16_t usPacketId );

/**
 * @brief Disconnect a MQTT session.
 *
 * @param[in] xContext Initialized MQTT context.
 *
 * @return An MQTTResult_t with the result of the operation.
 */
MQTTStatus_t AwsIoTMQTT_Disconnect( MQTTContext_t * xContext );


/**
 * @brief Loop to receive packets from the transport interface. Handles keep
 * alive.
 *
 * @param[in] xContext Initialized MQTT context.
 * @param[in] ulMilliseconds Minimum time in milliseconds that the process loop will
 * run, unless an error occurs.
 *
 * @return An MQTTResult_t with the result of the operation.
 */
MQTTStatus_t AwsIoTMQTT_ProcessLoop( MQTTContext_t * xContext,
                                       uint32_t ulMilliseconds );

/**
 * @brief Get a packet ID.
 *
 * @param[in] xContext Initialized MQTT context.
 *
 * @return A non-zero number.
 */
uint16_t AwsIoTMQTT_GetPacketId( MQTTContext_t * xContext );


/**
 * @brief Parses the payload of a MQTT SUBACK packet that contains status codes
 * corresponding to topic filter subscription requests from the original
 * subscribe packet.
 *
 * Each return code in the SUBACK packet corresponds to a topic filter in the
 * SUBSCRIBE Packet being acknowledged.
 * The status codes can be one of the following:
 *  - 0x00 - Success - Maximum QoS 0
 *  - 0x01 - Success - Maximum QoS 1
 *  - 0x02 - Success - Maximum QoS 2
 *  - 0x80 - Failure
 *
 * @param[in] pxSubackPacket The SUBACK packet whose payload is to be parsed.
 * @param[out] ppucPayloadStart This is populated with the starting address
 * of the payload (or return codes for topic filters) in the SUBACK packet.
 * @param[out] pxPayloadSize This is populated with the size of the payload
 * in the SUBACK packet. It represents the number of topic filters whose
 * SUBACK status is present in the packet.
 *
 * @return An MQTTResult_t with the result of the operation.
 */
MQTTStatus_t AwsIoTMQTT_GetSubAckStatusCodes( const MQTTPacketInfo_t * pxSubackPacket,
                                                uint8_t ** ppucPayloadStart,
                                                size_t * pxPayloadSize );

#endif /* AWS_IOT_MQTT_H */
